/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SuperSlot } from "./SuperSlot";
export * as factories from "./factories";
export { SuperSlot__factory } from "./factories/SuperSlot__factory";
